package io.specmatic.gradle.versioninfo

import org.gradle.api.java.archives.Manifest

private const val COMMENT = """this file is auto-generated by the specmatic gradle plugin. Any changes will be lost!"""

data class ProjectVersionInfo(
    val version: String,
    val gitCommit: String,
    val group: String,
    val name: String,
    val isRootProject: Boolean,
    val timestamp: String?
) {
    fun toKotlinClass(): String {
        return """
            // $COMMENT
            package ${kotlinPackage()}

            object VersionInfo {
                val version = "$version"
                val gitCommit = "$gitCommit"
                val gitShortCommit = "${shortCommit()}"
                val group = "$group"
                val name = "$name"
                ${maybeKotlinTimestamp()}
                
                fun describe() = "v${version}(${shortCommit()})${if (timestamp != null) " built at $timestamp" else ""}"
            }
        """.trimIndent()
    }

    private fun shortCommit() = gitCommit.take(8)

    fun packageDir() = kotlinPackage().replace(".", "/")
    fun kotlinFilePath() = "${packageDir()}/VersionInfo.kt"
    fun propertiesFilePath() = "${packageDir()}/version.properties"

    fun kotlinPackage(): String {
        if (isRootProject) {
            return group.lowercase().replace("[^a-zA-Z0-9]".toRegex(), ".")
        }
        return "${group}.${name}".lowercase().replace("[^a-zA-Z0-9]".toRegex(), ".")
    }


    fun toPropertiesFile(): String {
        return """
            # $COMMENT
            version=$version
            gitCommit=$gitCommit
            gitShortCommit=${shortCommit()}
            group=$group
            name=$name
            ${maybePropertyTimestamp()}
        """.trimIndent()
    }

    fun addToManifest(manifest: Manifest) {
        if (timestamp != null) {
            manifest.attributes["x-specmatic-compile-timestamp"] = timestamp
        }

        manifest.attributes["x-specmatic-version"] = version
        manifest.attributes["x-specmatic-group"] = group
        manifest.attributes["x-specmatic-name"] = name
        manifest.attributes["x-specmatic-git-sha"] = gitCommit
        manifest.attributes["x-specmatic-git-short-sha"] = shortCommit()
    }

    private fun maybeKotlinTimestamp() = if (timestamp != null) "val timestamp = \"$timestamp\"" else ""
    private fun maybePropertyTimestamp() = if (timestamp != null) "timestamp=$timestamp" else ""

}
