package io.specmatic.gradle.artifacts

import io.specmatic.gradle.license.pluginInfo
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.bundling.AbstractArchiveTask

// By default, JAR files generated by Gradle for a single project with the same source code may not be identical to each other
// It is desirable, especially for caching and reproducibility, to ensure that the generated JAR files are identical
// The generated artifact generally changes because it captures timestamps of each file, and the order may vary.
// We force the Gradle build to generate reproducible artifacts by ensuring that the timestamps are not captured and the order is fixed.
class EnsureReproducibleArtifactsPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        target.tasks.withType(AbstractArchiveTask::class.java).configureEach {
            target.pluginInfo("Ensuring that $path generates reproducible artifacts")
            isPreserveFileTimestamps = false
            isReproducibleFileOrder = true
        }
    }
}
