package io.specmatic.gradle.artifacts

import io.specmatic.gradle.pluginDebug
import org.gradle.api.Project
import org.gradle.api.file.DuplicatesStrategy
import org.gradle.api.tasks.bundling.AbstractArchiveTask

// By default, JAR files generated by Gradle for a single project with the same source code may not be identical to each other
// It is desirable, especially for caching and reproducibility, to ensure that the generated JAR files are identical
// The generated artifact generally changes because it captures timestamps of each file, and the order may vary.
// We force the Gradle build to generate reproducible artifacts by ensuring that the timestamps are not captured and the order is fixed.
class EnsureReproducibleArtifacts(project: Project) {
    init {
        project.allprojects.forEach(::configure)
    }

    private fun configure(project: Project) {
        project.afterEvaluate {
            project.tasks.withType(AbstractArchiveTask::class.java).configureEach(::configureTask)
        }
    }

    private fun configureTask(archiveTask: AbstractArchiveTask) {
        pluginDebug("Ensuring that ${archiveTask.path} generates reproducible artifacts")
        archiveTask.includeEmptyDirs = false
        archiveTask.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        archiveTask.isPreserveFileTimestamps = false
        archiveTask.isReproducibleFileOrder = true
    }
}