package io.specmatic.gradle.vuln.dto

import com.fasterxml.jackson.annotation.JsonProperty

// auto generated by github copilot. Don't ask :)

data class VulnerabilityReport(
    @field:JsonProperty("SchemaVersion") val schemaVersion: Int,
    @field:JsonProperty("CreatedAt") val createdAt: String,
    @field:JsonProperty("ArtifactName") val artifactName: String,
    @field:JsonProperty("ArtifactType") val artifactType: String,
    @field:JsonProperty("Results") val results: List<Result>
)

data class Result(
    @field:JsonProperty("Target") val target: String,
    @field:JsonProperty("Class") val clazz: String,
    @field:JsonProperty("Type") val type: String,
    @field:JsonProperty("Vulnerabilities") val vulnerabilities: List<Vulnerability>
)

data class Vulnerability(
    @field:JsonProperty("VulnerabilityID") val vulnerabilityId: String,
    @field:JsonProperty("PkgID") val pkgId: String,
    @field:JsonProperty("PkgName") val pkgName: String,
    @field:JsonProperty("PkgIdentifier") val pkgIdentifier: PkgIdentifier,
    @field:JsonProperty("InstalledVersion") val installedVersion: String,
    @field:JsonProperty("Status") val status: String,
    @field:JsonProperty("SeveritySource") val severitySource: String,
    @field:JsonProperty("PrimaryURL") val primaryUrl: String,
    @field:JsonProperty("DataSource") val dataSource: DataSource,
    @field:JsonProperty("Title") val title: String,
    @field:JsonProperty("Description") val description: String,
    @field:JsonProperty("Severity") val severity: String,
    @field:JsonProperty("CweIDs") val cweIds: List<String>,
    @field:JsonProperty("VendorSeverity") val vendorSeverity: Map<String, Int>,
    @field:JsonProperty("CVSS") val cvss: Map<String, Cvss>,
    @field:JsonProperty("References") val references: List<String>,
    @field:JsonProperty("PublishedDate") val publishedDate: String,
    @field:JsonProperty("LastModifiedDate") val lastModifiedDate: String
)

data class PkgIdentifier(
    @field:JsonProperty("PURL") val purl: String,
    @field:JsonProperty("UID") val uid: String,
    @field:JsonProperty("BOMRef") val bomRef: String
)

data class DataSource(
    @field:JsonProperty("ID") val id: String,
    @field:JsonProperty("Name") val name: String,
    @field:JsonProperty("URL") val url: String
)

data class Cvss(
    @field:JsonProperty("V3Vector") val v3Vector: String, @field:JsonProperty("V3Score") val v3Score: Double
)
